version: '3.5'

networks:
  nginx-php-mysql:

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container-gshock
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/project
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
      - mysql-service
    networks:
      - nginx-php-mysql

  php-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php-container-gshock
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/project
    networks:
      - nginx-php-mysql

  mysql-service:
    image: mysql:8
    container_name: mysql-container-gshock
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=db
    networks:
      - nginx-php-mysql